admin_panel/urls.py
# admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('hr_dashboard/', views.hr_dashboard, name='hr_dashboard'),
    path('management_dashboard/', views.management_dashboard, name='management_dashboard'),
    # Add more URLs for other custom admin panel views as needed
]

employee_management/urls.py
# employee_management/urls.py

from django.contrib import admin
from django.urls import path, include
from JobListings.views import show_resume, mail_send
from email_sender.views import show_mail_attachment

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('/', admin.site.urls),
    
    # Include the admin_panel URLs
    path('admin_panel/', include('admin_panel.urls')),
    path('', include('frontend_app.urls')),
    path('resumes/<str:resume_name>/', show_resume),
    path('attachments/<str:attachment_name>/', show_mail_attachment),
    path('mail/', mail_send),
    # Add other project-specific URLs here
]

frontend_app/urls.py
# admin_panel/urls.py
from django.urls import path
from . import views
from frontend_app.views import show_jd


app_name = 'frontend_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('notfound/', views.notfound, name='notfound'),
    path('team/', views.team, name='team'),
    path('blog/', views.blog, name='blog'),
    path('career/', views.career, name='career'),
    path('get_job_form/', views.get_job_form, name='get_job_form'),
    path('job_opening_form/<int:job_id>/', views.job_opening_form, name='job_opening_form'),
    path('show_jd/<str:jd_file_name>/', show_jd),

    # Add more URLs for other custom admin panel views as needed
]

templates/frontend_design/404notfound.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
    <style>
        body {
            font-family: 'Arvo', serif;
            background: #ABCDEF;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 90vh;
            transition: 1s;
        }

        .error {
            color: #20293F;
            box-shadow: 0 5px 0px -2px #20293F;
            text-align: center;
            animation: fadein 1.2s ease-in;
        }

        .error>.code {
            font-size: 10.5em;
            text-shadow: 0 6px 1px rgba(0, 0, 0, 0.0980392), 0 0 5px rgba(0, 0, 0, 0.0980392), 0 1px 3px rgba(0, 0, 0, 0.298039), 0 3px 5px rgba(0, 0, 0, 0.2), 0 5px 10px rgba(0, 0, 0, 0.247059), 0 10px 10px rgba(0, 0, 0, 0.2), 0 20px 20px rgba(0, 0, 0, 0.14902);
            margin: 0;
        }

        .error>.desc {
            text-shadow: 0px 3px 5px rgba(0, 0, 0, 0.5), 0px 6px 20px rgba(0, 0, 0, 0.3);
            font-weight: 400;
        }

        @keyframes fadein {
            0% {
                margin-top: -50px;
                opacity: 0;
            }

            50% {
                opacity: 0.5;
            }

            100% {
                opacity: 1;
            }
        }

        footer {
            position: absolute;
            bottom: 0px;
        }
    </style>
</head>

<body>
    <div class='error'>
        <h1 class='code'>404</h1>
        <h2 class='desc'>Ops... There's something wrong.</h2>
        <a href="{% url 'frontend_app:index'%}">Home</a>

    </div>
    <footer>
        <p>Global Smart Solutions</p>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/frontend_design/about.html
<style>
  #about {
    color: #16D5FF ; 
    
}
@media (max-width: 786px) {
    #img_about {
        display: none;
    }
    .container-fluid.hero-header{
        padding-bottom: 0 !important;
        margin-bottom: 0 !important;
    } 
}
</style>
{% load static %}

{% include "frontend_design/header.html" %}


   <!-- Header Start -->
   <div class="container-fluid hero-header bg-light py-5 mb-5" style="background-color:white">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6">
                <h1 class="display-4 mb-3 animated slideInDown">About Us</h1>
                <nav aria-label="breadcrumb animated slideInDown">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="{% url 'frontend_app:index'%}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">About Us</li>
                    </ol>
                </nav>
            </div>
            <div class="col-lg-6 animated fadeIn">
                <img id="img_about" class="img-fluid animated pulse infinite" style="animation-duration: 3s;" src="https://netrinoimages.s3.eu-west-2.amazonaws.com/2013/01/12/141473/273227/389_semi_truck_3d_model_c4d_max_obj_fbx_ma_lwo_3ds_3dm_stl_2865277_o.jpg"
                    alt="">
            </div>
        </div>
    </div>
</div>
<!-- Header End -->


<!-- About Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
                <img class="img-fluid" src="https://netrinoimages.s3.eu-west-2.amazonaws.com/2013/01/12/141473/273227/389_semi_truck_3d_model_c4d_max_obj_fbx_ma_lwo_3ds_3dm_stl_2865277_o.jpg" alt="">
            </div>
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
                <div class="h-100">
                    <h1 class="display-6">About Us</h1>
                    <p class="text-primary fs-5 mb-4">The Most Trusted Cryptocurrency Platform</p>
                    <p>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos.
                        Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet
                    </p>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet
                        diam et eos. Clita erat ipsum et lorem et sit.</p>
                    <div class="d-flex align-items-center mb-2">
                        <i class="fa fa-check bg-light text-primary btn-sm-square rounded-circle me-3 fw-bold"></i>
                        <span>Tempor erat elitr rebum at clita</span>
                    </div>
                    <div class="d-flex align-items-center mb-2">
                        <i class="fa fa-check bg-light text-primary btn-sm-square rounded-circle me-3 fw-bold"></i>
                        <span>Tempor erat elitr rebum at clita</span>
                    </div>
                    <div class="d-flex align-items-center mb-4">
                        <i class="fa fa-check bg-light text-primary btn-sm-square rounded-circle me-3 fw-bold"></i>
                        <span>Tempor erat elitr rebum at clita</span>
                    </div>
                    <a class="btn btn-primary py-3 px-4" href="">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->


{% include "frontend_design/footer.html" %}

templates/frontend_design/blog.html
<style>
    #blog {
      color: #16D5FF ; /* Red color */
  }
  </style>
  {% load static %}
  
  {% include "frontend_design/header.html" %}




  {% include "frontend_design/footer.html" %}



  

templates/frontend_design/career.html
<style>
  #career {
    color: #16D5FF;
    /* Red color */
  }
</style>
{% load static %}

{% include "frontend_design/header.html" %}

<!-- Service Start -->
<div class="container-xxl bg-light py-5 my-5">
  <div class="container py-5">
    <div class="text-center mx-auto wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
      <h1 class="display-6">Opening</h1>
      <p class="text-primary fs-5 mb-5">Lorem ipsum dolor sit amet consectetur adipis</p>
    </div>
    <div class="row g-4">
      {% for job in joblisting %}
      {% if job.currently_accepting %}
      <div class="col-lg-4 col-md-6 wow fadeInUp " data-wow-delay="0.1s">
        <div class="service-item bg-white p-5">
            <h5 class="mb-3">{{ job.title }}</h5>
            <p>{{job.description}}</p>
            <a href="{% url 'frontend_app:job_opening_form' job_id=job.id %}" class="btn btn-primary w-25 d-block ms-auto" type="submit">Apply</a>
          
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
<!-- Service End -->






{% include "frontend_design/footer.html" %}

templates/frontend_design/contact.html
<style>
    #contact {
      color: #16D5FF ; /* Red color */
  }
  </style>
  {% load static %}
  
  {% include "frontend_design/header.html" %}
    
    
    <!-- Header Start -->
    <div class="container-fluid hero-header bg-light py-5 mb-5">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6">
                    <h1 class="display-4 mb-3 animated slideInDown">Contact Us</h1>
                    <nav aria-label="breadcrumb animated slideInDown">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="{% url 'frontend_app:index'%}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 animated fadeIn">
                    <img class="img-fluid animated pulse infinite" style="animation-duration: 3s;" src="https://netrinoimages.s3.eu-west-2.amazonaws.com/2013/01/12/141473/273227/389_semi_truck_3d_model_c4d_max_obj_fbx_ma_lwo_3ds_3dm_stl_2865277_o.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 mb-5 wow fadeInUp" data-wow-delay="0.1s">
                <div class="col-lg-6">
                    <h1 class="display-6">Contact Us</h1>
                    <p class="text-primary fs-5 mb-0">If You Have Any Query, Please Contact Us</p>
                </div>
                <div class="col-lg-6 text-lg-end">
                    <a class="btn btn-primary py-3 px-4" href="">Say Hello</a>
                </div>
            </div>
            <div class="row g-5">
                <div class="col-lg-5 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <p class="mb-2">Our office:</p>
                    <h4>123 Street, New York, USA</h4>
                    <hr class="w-100">
                    <p class="mb-2">Call us:</p>
                    <h4>+012 345 6789</h4>
                    <hr class="w-100">
                    <p class="mb-2">Mail us:</p>
                    <h4>info@example.com</h4>
                    <hr class="w-100">
                    <p class="mb-2">Follow us:</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-primary rounded-circle me-2" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-7 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                    <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>
                    <form>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                                    <label for="name">Your Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                                    <label for="email">Your Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" placeholder="Subject">
                                    <label for="subject">Subject</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 100px"></textarea>
                                    <label for="message">Message</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary py-3 px-4" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    <!-- Google Map Start -->
    <div class="container-xxl py-5 px-0 wow fadeInUp" data-wow-delay="0.1s">
        <iframe class="w-100 mb-n2" style="height: 450px;"
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
            frameborder="0" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- Google Map End -->

    {% include "frontend_design/footer.html" %}

templates/frontend_design/footer.html
{% load static %}
 
 <!-- Footer Start -->
 <div class="container-fluid bg-light footer pt-5 wow fadeIn" data-wow-delay="0.1s">
  <div class="container py-5">
      <div class="row g-5">
          <div class="col-md-6">
              <h1 class="text-primary mb-4">
                {% comment %} <img class="img-fluid me-2" src="static/assets/img/icon-1.png" alt=""
                      style="width: 45px;"> {% endcomment %}
                      GSS</h1>
              <span>Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed
                  stet lorem sit clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum
                  et lorem et sit.</span>
          </div>
          <div class="col-md-6">
              <h5 class="mb-4">Newsletter</h5>
              <p>Clita erat ipsum et lorem et sit, sed stet lorem sit clita.</p>
              <div class="position-relative">
                  <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text"
                      placeholder="Your email">
                  <button type="button"
                      class="btn btn-primary py-2 px-3 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
              </div>
          </div>
          <div class="col-lg-3 col-md-6">
              <h5 class="mb-4">Get In Touch</h5>
              <p><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
              <p><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
              <p><i class="fa fa-envelope me-3"></i>info@example.com</p>
          </div>
          <div class="col-lg-3 col-md-6">
              <h5 class="mb-4">Our Services</h5>
              <a class="btn btn-link" href="">Currency Wallet</a>
              <a class="btn btn-link" href="">Currency Transaction</a>
              <a class="btn btn-link" href="">Bitcoin Investment</a>
              <a class="btn btn-link" href="">Token Sale</a>
          </div>
          <div class="col-lg-3 col-md-6">
              <h5 class="mb-4">Quick Links</h5>
              <a class="btn btn-link" href="{% url 'frontend_app:about'%}">About Us</a>
              <a class="btn btn-link" href="{% url 'frontend_app:contact'%}">Contact Us</a>
              <a class="btn btn-link" href="{% url 'frontend_app:services'%}">Our Services</a>
              <a class="btn btn-link" href="">Terms & Condition</a>
          </div>
          <div class="col-lg-3 col-md-6">
              <h5 class="mb-4">Follow Us</h5>
              <div class="d-flex">
                  <a class="btn btn-square rounded-circle me-1" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-square rounded-circle me-1" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-square rounded-circle me-1" href=""><i class="fab fa-youtube"></i></a>
                  <a class="btn btn-square rounded-circle me-1" href=""><i class="fab fa-linkedin-in"></i></a>
              </div>
          </div>
      </div>
  </div>
  <div class="container-fluid copyright">
      <div class="container">
          <div class="row">
              <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                  &copy; <a href="#">Your Site Name</a>, All Right Reserved.
              </div>
              <div class="col-md-6 text-center text-md-end">
                  <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                  Designed By <a href="https://htmlcodex.com">HTML Codex</a> Distributed By <a
                      href="https://themewagon.com">ThemeWagon</a>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i
      class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'assets/lib/wow/wow.min.js'%}"></script>
<script src="{% static 'assets/lib/easing/easing.min.js'%}"></script>
<script src="{% static 'assets/lib/waypoints/waypoints.min.js'%}"></script>
<script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/lib/counterup/counterup.min.js'%}"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

<!-- alertify message -->
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
{% for message_flash in messages %}
<script>
    alertify.set('notifier', 'position', 'top-right');
    alertify.success('{{ message_flash }}');
</script>
{% endfor %}
<!-- Template Javascript -->
<script src="{% static 'assets/js/main.js'%}"></script>
</body>

</html>

templates/frontend_design/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    

<head>
    <meta charset="utf-8">
    <title>GSS - Global Smart Solutions</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'assets/img/favicon.icon'%}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Roboto:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    
    <link href="{% static 'assets/lib/animate/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'assets/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- alertify message -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
    <style>
        body{
            background-color: #F2F8FE;
        }
    </style>
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0 px-4 px-lg-5">
        <a href="{% url 'frontend_app:index'%}" class="navbar-brand d-flex align-items-center">
            <h2 class="m-0 text-primary">
                {% comment %} <img class="img-fluid me-2" src="{% static 'assets/img/icon-1.jpg'%}" alt=""
                    style="width: 45px;"> {% endcomment %}
                    GSS</h2>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-4 py-lg-0">
                <a href="{% url 'frontend_app:index'%}" class="nav-item nav-link" id="home">Home</a>
                <a href="{% url 'frontend_app:about'%}" class="nav-item nav-link " id="about">About</a>
                <a href="{% url 'frontend_app:services'%}" class="nav-item nav-link "id="services">Services</a>
                <a href="{% url 'frontend_app:career'%}" class="nav-item nav-link active_" id="career">Career</a>
                <a href="{% url 'frontend_app:team'%}" class="nav-item nav-link active_" id="team">Team</a>
                <a href="{% url 'frontend_app:blog'%}" class="nav-item nav-link active_" id="blog">Blog</a>

                {% comment %} <div class="nav-item dropdown">
                    <a href="#" class="nav-link active_ dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu shadow-sm m-0">
                        <a href="feature.html" class="dropdown-item">Feature</a>
                        <a href="token.html" class="dropdown-item">Token Sale</a>
                        <a href="faq.html" class="dropdown-item">FAQs</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div> {% endcomment %}
                <a href="{% url 'frontend_app:contact'%}" class="nav-item nav-link active_" id="contact">Contact</a>
            </div>
            <div class="h-100 d-lg-inline-flex align-items-center d-none">
                <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i
                        class="fab fa-facebook-f"></i></a>
                <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i
                        class="fab fa-twitter"></i></a>
                <a class="btn btn-square rounded-circle bg-light text-primary me-0" href=""><i
                        class="fab fa-linkedin-in"></i></a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->

templates/frontend_design/job_opening_form.html
{% load static %}

{% include "frontend_design/header.html" %}



<!-- Contact Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5">
            <div class="col-md-3"></div>
            <div class="col-lg-7 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                <h4 class="mb-4">Job Application Form</h4>
                <form action="{% url 'frontend_app:get_job_form'%}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="text" class="form-control" name="name" id="name" placeholder="Your Name" required>
                                <label for="name">Your Name</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                                <label for="email">Your Email</label>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="url" id="linkedin" name="linkedin_profile" class="form-control">
                                <label for="linkedin">LinkedIn Profile:</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="url" id="github" name="github_profile" class="form-control">
                                <label for="github">GitHub Profile:</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="file" name="resume" style="cursor: pointer;" class="form-control" id="resume" accept=".pdf" required >
                                <label for="resume">Resume (PDF):</label>                                
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-floating">
                                <input type="text" readonly id="appliedfor" value="{{title}}" name="applied_for" class="form-control">
                                <label for="applied_for">Applied For:</label>
                            <a href="/{{description_file}}" target="_blank" style="color:black">Job Description PDF</a>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button class="btn btn-primary py-2 rounded ms-auto d-block w-100 px-4" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-3"></div>

        </div>
    </div>
</div>
<!-- Contact End -->



{% include "frontend_design/footer.html" %}

templates/frontend_design/team.html
<style>
    #team {
      color: #16D5FF ; /* Red color */
  }
  </style>
  {% load static %}
  
  {% include "frontend_design/header.html" %}




  {% include "frontend_design/footer.html" %}



  